[package]
name = "package-vigilant"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
serde_json = "1.0.140"
reqwest = { version = "0.12.15", features = ["blocking"] }
base64 = "0.22.1"
ml-dsa = "0.1.0-pre.2"
rand = "0.9.0"
